### ISSUE TITLE
Enable geyser:true in config can't use ForcePack

### ISSUE THREAD

**Issue by NotKillerGod** [SamB440/ForcePack#19]
version:paper1.19.2

Could not pass event PlayerJoinEvent to ForcePack v1.2.7
java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
        at com.convallyria.forcepack.api.utils.GeyserUtil.isBedrockPlayer(GeyserUtil.java:10) ~[ForcePack-1.2.7.jar:?]
        at com.convallyria.forcepack.spigot.listener.ResourcePackListener.onPlayerJoin(ResourcePackListener.java:116) ~[ForcePack-1.2.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor179.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-"476ef25"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.api.FloodgateApi
        ... 22 more

**Comment by SamB440** [comment]
Only enable that if you use Geyser. You need the Geyser plugin installed.

**Comment by NotKillerGod** [comment]
> 仅当您使用间歇泉时启用它。您需要安装间歇泉插件。

I had use Geyser-Bungeecord and Geyser_standalone

**Comment by SamB440** [comment]
You need floodgate (https://wiki.geysermc.org/floodgate/) installed on the backend server

**Comment by justincps** [comment]
@SamB440
I’m using both Floodgate and Geyser, and I’ve enabled Geyser support in the config.
When I join from Java Edition, everything works perfectly — the locally hosted resource pack loads through the plugin.
However, when I join from Bedrock, nothing happens: I can move around, no resource pack starts downloading.
I joined with my linked Floodgate account, so the server recognizes that I’m using the same account on Bedrock as on Java.

How can I fix this? - Thanks!
