### ISSUE TITLE
Crash when starting

### ISSUE THREAD

**Issue by Le-noirrateur** [SamB440/ForcePack#29]
### Hello,
So i tried to load the plugin but there's an error **who occurred** :

`com.convallyria.forcepack.libs.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: version too high ()
`

I don't know how to fix it.

> Here's the server config :

- **Plugins :**

1.  MCE - SMP plugin ( Created by my self and there no problem with it ).
2.  TCP Shield.
3.  Skin restorer.
4.  Force Pack ( the plugin ).

- **Info :**

     Spigot - Bukkit 1.20.1.
     Force Pack version : 1.2.9

**Comment by SamB440** [comment]
Provide the full crash report

**Comment by ABIZU-fluffyoffciel** [comment]
So, here the error :

[09:04:57] [Server thread/INFO]: [ForcePack] Enabling ForcePack v1.2.9
[09:04:57] [Server thread/WARN]: [ForcePack] Could not save en_gb.yml to plugins\ForcePack\lang\en_gb.yml because en_gb.yml already exists.
[09:04:57] [Server thread/INFO]: [ForcePack] Generated en_gb.yml
[09:04:57] [Server thread/WARN]: [ForcePack] Could not save zh_cn.yml to plugins\ForcePack\lang\zh_cn.yml because zh_cn.yml already exists.
[09:04:57] [Server thread/INFO]: [ForcePack] Generated zh_cn.yml
[09:04:57] [Server thread/ERROR]: Error occurred while enabling ForcePack v1.2.9 (Is it up to date?)
com.convallyria.forcepack.libs.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: version too high ()
        at com.convallyria.forcepack.libs.commandframework.bukkit.BukkitCommandManager.registerBrigadier(BukkitCommandManager.java:343) ~[?:?]
        at com.convallyria.forcepack.libs.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:125) ~[?:?]
        at com.convallyria.forcepack.spigot.command.Commands.<init>(Commands.java:38) ~[?:?]
        at com.convallyria.forcepack.spigot.ForcePackSpigot.registerCommands(ForcePackSpigot.java:212) ~[?:?]
        at com.convallyria.forcepack.spigot.ForcePackSpigot.onEnable(ForcePackSpigot.java:69) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.reload(CraftServer.java:962) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
        at org.bukkit.Bukkit.reload(Bukkit.java:832) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:871) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:856) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:389) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
and /ver output : 

[09:06:17] [Server thread/INFO]: This server is running CraftBukkit version 3814-Spigot-64b565e-c1279f7 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
[09:06:17] [Server thread/INFO]: Checking version, please wait...
[09:06:17] [Thread-13/INFO]: You are running the latest version

**Comment by SamB440** [comment]
Caused by Spigot having skill issue against Paper superiority

(from a search on incendo's Discord)
> [21:51] jmp: oh, you want paper command manager
[21:52] jmp: and checking for NATIVE_BRIGADIER
[..]
[21:54] jmp: no, but no one uses spigot anyways
[21:55] jmp: brigadier just isn't supported on spigot in modern versions

**Comment by ABIZU-fluffyoffciel** [comment]
So, how i can fix it, is it a problem with the API version, bc with my own plugin the maven don't accept 1.20.1 Spigot API, 1.20, 1.19.3, 1.19.2 and 1.19.1 but 1.19 work...

( i use Intellij IDEA Ultimate )

**Comment by SamB440** [comment]
> So, how i can fix it, is it a problem with the API version? Bc with my own plugin maven don't accept 1.20.1 Spigot API, 1.20, 1.19.3, 1.19.2 and 1.19.1 but 1.19 work...
> 
> ( i use Intellij IDEA Ultimate )

I believe I need to check that `NATIVE_BRIGADIER` can be used, rather than just `BRIGADIER`, but obviously then you won't get the nicely formatted commands by using Spigot, but, that's their problem.

Don't know the issue with your plugin, but, subversions (e.g 1.19.3) are not valid api versions, and 1.20 probably doesn't work because you haven't quoted it like: `api-version '1.20'`, as yaml without the quotes will parse it as 1.2.

**Comment by SamB440** [comment]
Please let me know whether this new jar works [libs.zip](https://github.com/SamB440/ForcePack/files/11859473/libs.zip)

**Comment by ABIZU-fluffyoffciel** [comment]
Sorry for the delay,
So i added the version and when it's start there no crash.

![image](https://github.com/SamB440/ForcePack/assets/69718661/02fcd5dc-5ddc-4c98-84ca-118d35e340f5)
![image](https://github.com/SamB440/ForcePack/assets/69718661/5b12396c-7409-4b40-8e30-20c9648a1661)

and it's **working correctly**.
Thanks you.

**Comment by ABIZU-fluffyoffciel** [comment]
Thanks you again, that unlock me for the rest part of coding.

**Comment by ABIZU-fluffyoffciel** [comment]
> > So, how i can fix it, is it a problem with the API version? Bc with my own plugin maven don't accept 1.20.1 Spigot API, 1.20, 1.19.3, 1.19.2 and 1.19.1 but 1.19 work...
> > ( i use Intellij IDEA Ultimate )
> 
> I believe I need to check that `NATIVE_BRIGADIER` can be used, rather than just `BRIGADIER`, but obviously then you won't get the nicely formatted commands by using Spigot, but, that's their problem.
> 
> Don't know the issue with your plugin, but, subversions (e.g 1.19.3) are not valid api versions, and 1.20 probably doesn't work because you haven't quoted it like: `api-version '1.20'`, as yaml without the quotes will parse it as 1.2.

ahhh so just because the `api-version` is not under '' that doesn't work... That is annoying
