### ISSUE TITLE
console error with player disconnect

### ISSUE THREAD

**Issue by T4B999** [SamB440/ForcePack#3]
[12:20:26 ERROR]: Could not pass event PlayerQuitEvent to StackMob v5.8.2
java.lang.NullPointerException: Cannot invoke "uk.antiperson.stackmob.packets.PlayerWatcher.stopWatching()" because "playerWatcher" is null
at uk.antiperson.stackmob.packets.PlayerManager.stopWatching(PlayerManager.java:37) ~[StackMob-5.8.2.jar:?]
at uk.antiperson.stackmob.listeners.PlayerArmorStandListener.onQuit(PlayerArmorStandListener.java:18) ~[StackMob-5.8.2.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor539.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:git-Purpur-1748]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:624) ~[purpur-1.19.1.jar:git-Purpur-1748]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2219) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:572) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:513) ~[?:?]
at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:525) ~[purpur-1.19.1.jar:git-Purpur-1748]
at com.convallyria.forcepack.spigot.listener.ResourcePackListener.lambda$onStatus$2(ResourcePackListener.java:56) ~[ForcePack-1.2.1.jar:?]
at com.convallyria.forcepack.spigot.listener.ResourcePackListener.ensureMainThread(ResourcePackListener.java:117) ~[ForcePack-1.2.1.jar:?]
at com.convallyria.forcepack.spigot.listener.ResourcePackListener.onStatus(ResourcePackListener.java:56) ~[ForcePack-1.2.1.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:git-Purpur-1748]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleResourcePackResponse(ServerGamePacketListenerImpl.java:2178) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:24) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:10) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.1.jar:git-Purpur-1748]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.1.jar:git-Purpur-1748]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.1.jar:git-Purpur-1748]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.1.jar:git-Purpur-1748]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.1.jar:git-Purpur-1748]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1434) ~[purpur-1.19.1.jar:git-Purpur-1748]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[purpur-1.19.1.jar:git-Purpur-1748]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1748]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by T4B999** [comment]
this is stack mob issue or forcepack issue ?

**Comment by SamB440** [comment]
Stackmob issue
