### ISSUE TITLE
unable to move when using forcepack on 1.20.2 cracked server

### ISSUE THREAD

**Issue by kristupas098** [SamB440/ForcePack#43]
[15:11:21] [Server thread/ERROR]: Could not pass event PlayerResourcePackStatusEvent to ForcePack v1.2.9
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.PlayerConnection.b(net.minecraft.network.protocol.Packet)" because "org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.getHandle().c" is null
	at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.sendTitle(CraftPlayer.java:2668) ~[paper-1.20.2.jar:git-Paper-260]
	at com.convallyria.forcepack.spigot.listener.ResourcePackListener.onStatus(ResourcePackListener.java:81) ~[ForcePack-1.2.9.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor177.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-260]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-260]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-260]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:187) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleResourcePackResponse(ServerConfigurationPacketListenerImpl.java:100) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:24) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:10) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-260]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by SamB440** [comment]
Doesn't seem like a ForcePack problem, either an incompatible plugin doing something stupid or there is a bug in spigot/paper. You can try disabling send titles in the config.
