### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to forcepack

### ISSUE THREAD

**Issue by condblock** [SamB440/ForcePack#49]
[23:22:27 ERROR]: Couldn't pass ProxyInitializeEvent to forcepack
java.lang.NullPointerException: Cannot invoke "com.convallyria.forcepack.velocity.config.VelocityConfig.getStringList(String)" because "resourcePack" is null
	at com.convallyria.forcepack.velocity.ForcePackVelocity.registerResourcePack(ForcePackVelocity.java:251) ~[?:?]
	at com.convallyria.forcepack.velocity.ForcePackVelocity.lambda$addResourcePacks$2(ForcePackVelocity.java:246) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at com.convallyria.forcepack.velocity.ForcePackVelocity.addResourcePacks(ForcePackVelocity.java:246) ~[?:?]
	at com.convallyria.forcepack.velocity.ForcePackVelocity.loadResourcePacks(ForcePackVelocity.java:214) ~[?:?]
	at com.convallyria.forcepack.velocity.ForcePackVelocity.onProxyInitialization(ForcePackVelocity.java:154) ~[?:?]
	at com.convallyria.forcepack.velocity.Lmbda$5.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-330.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-330.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-330.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by SamB440** [comment]
Broken config
