### ISSUE TITLE
Does not start after migration to another host

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [SamB440/ForcePack#59]
```
[20:53:47 ERROR]: Couldn't pass ProxyInitializeEvent to forcepack
java.lang.NullPointerException: Cannot invoke "com.convallyria.forcepack.velocity.config.VelocityConfig.getKeys()" because "root" is null
        at com.convallyria.forcepack.velocity.ForcePackVelocity.addResourcePacks(ForcePackVelocity.java:213) ~[?:?]
        at com.convallyria.forcepack.velocity.ForcePackVelocity.loadResourcePacks(ForcePackVelocity.java:195) ~[?:?]
        at com.convallyria.forcepack.velocity.ForcePackVelocity.onProxyInitialization(ForcePackVelocity.java:132) ~[?:?]
        at com.convallyria.forcepack.velocity.Lmbda$9.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-9450e660-b310)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-9450e660-b310)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-9450e660-b310)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```
 Velocity 3.3.0-SNAPSHOT (git-9450e660-b310)
 Latest version of plugin

**Comment by SamB440** [comment]
Your config.toml is invalid, it's missing either "groups" or "servers" section.

**Comment by SPAWNRYS-ban** [comment]
yes working
thanks
