### ISSUE TITLE
reload = error

### ISSUE THREAD

**Issue by FlameGrowl-wq** [SamB440/ForcePack#66]
I get this error every time i reload the plugin with /vforcepackreload
and the screen doesnt show 
but when i first tried it, it worked

java.lang.NullPointerException: Cannot invoke "com.convallyria.forcepack.velocity.handler.PackHandler.setPack(com.velocitypowered.api.proxy.Player, com.velocitypowered.api.proxy.ServerConnection)" because the return value of "com.convallyria.forcepack.velocity.ForcePackVelocity.getPackHandler()" is null
at com.convallyria.forcepack.velocity.command.ForcePackCommand.lambda$onReload$0(ForcePackCommand.java:45)
at java.base/java.util.Optional.ifPresent(Optional.java:178)
at com.convallyria.forcepack.velocity.command.ForcePackCommand.onReload(ForcePackCommand.java:44)
at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758)
at com.convallyria.forcepack.libs.cloud.annotations.MethodCommandExecutionHandler.executeFuture(MethodCommandExecutionHandler.java:88)
at com.convallyria.forcepack.libs.cloud.execution.ExecutionCoordinatorImpl.lambda$coordinateExecution$4(ExecutionCoordinatorImpl.java:121)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
at com.convallyria.forcepack.libs.cloud.execution.ExecutionCoordinatorImpl$NonSchedulingExecutor.execute(ExecutionCoordinatorImpl.java:53)
at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1184)
at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2352)
at com.convallyria.forcepack.libs.cloud.execution.ExecutionCoordinatorImpl.coordinateExecution(ExecutionCoordinatorImpl.java:104)
at com.convallyria.forcepack.libs.cloud.StandardCommandExecutor.executeCommand(StandardCommandExecutor.java:91)
at com.convallyria.forcepack.libs.cloud.StandardCommandExecutor.executeCommand(StandardCommandExecutor.java:65)
at com.convallyria.forcepack.libs.cloud.brigadier.CloudBrigadierCommand.run(CloudBrigadierCommand.java:65)
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:230)
at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:279)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by SamB440** [comment]
That error doesn't make sense, the real error is likely elsewhere

**Comment by FlameGrowl-wq** [comment]
but it's on your plug in

**Comment by SamB440** [comment]
I meant there should be another error, probably at startup

**Comment by SamB440** [comment]
You enabled the web server but you already have a service running on port 8080.
