### ISSUE TITLE
Plugin can't load

### ISSUE THREAD

**Issue by MatinHQ** [SamB440/ForcePack#70]
using latest version of velocity-ctd plugin can't be loaded

https://github.com/GemstoneGG/Velocity-CTD

`[11:29:32] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to forcepack 1.3.4
java.lang.UnsupportedOperationException: StampedConfig does not support valueMap() yet.
	at com.electronwill.nightconfig.core.concurrent.StampedConfig.valueMap(StampedConfig.java:473) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-e75ca601)]
	at com.convallyria.forcepack.velocity.config.VelocityConfig.getKeys(VelocityConfig.java:106) ~[?:?]
	at com.convallyria.forcepack.velocity.ForcePackVelocity.addResourcePacks(ForcePackVelocity.java:213) ~[?:?]
	at com.convallyria.forcepack.velocity.ForcePackVelocity.loadResourcePacks(ForcePackVelocity.java:192) ~[?:?]
	at com.convallyria.forcepack.velocity.ForcePackVelocity.onProxyInitialization(ForcePackVelocity.java:132) ~[?:?]
	at com.convallyria.forcepack.velocity.Lmbda$26.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-e75ca601)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:483) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-e75ca601)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:475) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-e75ca601)]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]`

**Comment by SamB440** [comment]
That sounds like a velocity-ctd problem then?

**Comment by MatinHQ** [comment]
not sure, it's only plugin have issues with CTD haven't tested with latest velocity

**Comment by R00tB33rMan** [comment]
> That sounds like a velocity-ctd problem then?

We use a newer dependency of NightConfig. Upgrading NightConfig on your end should be able to fix this issue. I'm planning to create a PR that upgrades a large array of dependencies, as Velocity is quite behind, and after some minor tweaks, I see no reason not to.

**Comment by SamB440** [comment]
I've bumped night-config, although I don't see how that would fix the problem

**Comment by MatinHQ** [comment]
issue still persist with 4.1.5
