### ISSUE TITLE
Having some trouble to start the plugin

### ISSUE THREAD

**Issue by Prozoon700** [SamB440/ForcePack#71]
`[14:19:31 WARN]: Error loading plugin ForcePack
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:93b0fa7:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:93b0fa7:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:93b0fa7:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:93b0fa7:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:93b0fa7:unknown]
        at net.md_5.bungee.BungeeCord.start(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:93b0fa7:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:93b0fa7:unknown]
        at net.md_5.bungee.Bootstrap.main(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:93b0fa7:unknown]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:93b0fa7:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:93b0fa7:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 13 more`

I haven't modified anything, the plugins is like when it's installed.

**Comment by SamB440** [comment]
Travertine? Bungee isn't supported

**Comment by Prozoon700** [comment]
I'm using XCord

**Comment by SamB440** [comment]
It doesn't matter - any Bungee implementation isn't supported, only Velocity

**Comment by Prozoon700** [comment]
Ahh okey. Thanks!
