### ISSUE TITLE
Error while loading resource pack

### ISSUE THREAD

**Issue by Ducki0210** [SamB440/ForcePack#79]
Hello, everyone is working properly but this error occur while downloading and rendering the resource pack

[12:34:30] [ForcePack - Task Executor #1/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass PlayerResourcePackStatusEvent to forcepack 1.3.6
java.lang.NullPointerException: Cannot invoke "com.convallyria.forcepack.velocity.config.VelocityConfig.getConfig(String)" because the return value of "com.convallyria.forcepack.velocity.config.VelocityConfig.getConfig(String)" is null
	at com.convallyria.forcepack.velocity.listener.ResourcePackListener.onPackStatus(ResourcePackListener.java:97) ~[?:?]
	at com.convallyria.forcepack.velocity.listener.Lmbda$14.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[server.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[server.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by SamB440** [comment]
You have an invalid config
