### ISSUE TITLE
Server fails to download pack

### ISSUE THREAD

**Issue by Bluebotlabz** [SamB440/ForcePack#9]
~~~
[INFO]: [Not Secure] [Server] --- accepted the resource pack!
[INFO]: [Not Secure] [Server] --- accepted the resource pack!
[INFO]: [Not Secure] [Server] --- failed to download the resource pack!
[ERROR]: Could not pass event PlayerResourcePackStatusEvent to ForcePack v1.2.5
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.remove(Object)" is null
        at com.convallyria.forcepack.spigot.listener.ResourcePackListener.tryValidateHacks(ResourcePackListener.java:100) ~[ForcePack-1.2.5.jar:?]
        at com.convallyria.forcepack.spigot.listener.ResourcePackListener.onStatus(ResourcePackListener.java:56) ~[ForcePack-1.2.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor69.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1835]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleResourcePackResponse(ServerGamePacketListenerImpl.java:2178) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
~~~

When I join the server, the pack doesn't download and the client sometimes gets kicked out, this time it didn't kick but this error was on the console

Any help is appreciated!

**Comment by SamB440** [comment]
Please enable debug mode and send the output

**Comment by SamB440** [comment]
It is indeed possible for this error to occur, but I only see it happening if the user is cheating. The error has been fixed. Anything else such as failed to download is unrelated and you should open a new issue with the details I asked for above.
